# =========================
# Base image
# =========================
FROM node:24-alpine3.21 AS base
WORKDIR /starter

# =========================
# STAGE 1: Install dependencies
# =========================
FROM base AS deps

COPY public ./public
COPY package*.json ./

# Install all dependencies (including dev dependencies)
RUN npm install

# =========================
# STAGE 2: Development runtime
# =========================
FROM base AS runner
WORKDIR /starter

# Copy node_modules from deps stage
COPY --from=deps /starter/node_modules ./node_modules

# Copy all source files
COPY . .

# Expose dev port
EXPOSE 8080

# Set environment
ENV NODE_ENV=development

# Default command
CMD ["npm", "start"]

